# config3.py

# API credentials
api_key = 'b4Cw5Z2a2uToBHunOedHBKabGhdn1pm2MA5PJALWF9nU7XJ6f2GrAKkijY4OdXYe'
api_secret = '1XyFpTQFkac5PJZYXysVSCcGKMkLPcqLzk8BOKWAmTc9kiQyMIK5hdrzbaw4cHXn'

# Telegram bot token and chat ID
bot_token = '7059673705:AAEPdxG0FuVarZLc2fqURr9W3Qb2NPDIc2c'
chat_id = '1434650273'

# Selected symbols (without 'USDT')
SELECTED_SYMBOLS = [
    'AAVEUSDT', 'ACEUSDT', 'ACHUSDT', 'ADAUSDT', 'AEVOUSDT', 'AGLDUSDT', 
    'ALGOUSDT', 'ALICEUSDT', 'ALPHAUSDT', 'ALTUSDT', 'AMBUSDT', 'APTUSDT',
    'ARBUSDT', 'ARKUSDT', 'ARPAUSDT', 'ARUSDT', 'ASTRUSDT', 'ATAUSDT', 
    'ATOMUSDT', 'AUCTIONUSDT', 'AVAXUSDT', 'AXLUSDT', 'AXSUSDT', 
    'BADGERUSDT', 'BAKEUSDT', 'BALUSDT', 'BANDUSDT', 'BATUSDT', 'BBUSDT'
]
